[versions]
# libraries
junit = "4.13.2"
kotlinx-serialization-json = "1.8.0"
kotlinx-serialization-xml = "0.90.0"
pdvrieze-serialization-xml = "0.90.3.0"
opentest4j = "1.3.0"

# plugins
changelog = "2.5.0"
intelliJPlatform = "2.10.5"
kotlin = "2.2.21"
kover = "0.9.3"
qodana = "2025.2.2"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinxSerializationJson = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinxSerializationXml = { group = "nl.pdvrieze.xmlutil", name = "serialization", version.ref = "pdvrieze-serialization-xml" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
